# Generated by Django 5.0 on 2024-03-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_lectureprogress_moduleprogress_userprogress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
