# Generated by Django 5.0 on 2024-04-07 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_lecture_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='completed_lectures',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='completed_modules',
        ),
        migrations.AddField(
            model_name='userprogress',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='lecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.lecture'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.module'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.topic'),
        ),
    ]
