# Generated by Django 5.0 on 2024-04-07 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_userprogress_completed_lectures_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.lecture'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.module'),
        ),
    ]
