# Generated by Django 5.0 on 2024-04-07 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_userprogress_completed_lectures_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='completed_topics',
            field=models.ManyToManyField(blank=True, null=True, related_name='completed_topic_progress', to='api.topic'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.topic'),
        ),
    ]
