# Generated by Django 5.0 on 2024-04-07 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userprogress_completed_topics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduleprogress',
            name='module',
        ),
        migrations.RemoveField(
            model_name='moduleprogress',
            name='user_progress',
        ),
        migrations.DeleteModel(
            name='LectureProgress',
        ),
        migrations.DeleteModel(
            name='ModuleProgress',
        ),
    ]
