# Generated by Django 5.0 on 2024-04-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_userprogress_quiz_results_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
