# Generated by Django 5.0 on 2024-05-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_userprogress_quiz_results_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='quiz_completitions',
            field=models.IntegerField(default=0),
        ),
    ]
