# Generated by Django 5.0 on 2024-05-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_userprogress_quiz_completitions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(default='', max_length=800),
        ),
    ]
